version: "3"
services:
  secure-open:
    build: .
    image: lapwat/secure-open
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${PATH_TO_DIRECTORY}:/app/data/secure:ro
    network_mode: none
    ipc: host
    environment:
      - DISPLAY=unix${DISPLAY}
    devices:
      - /dev/snd
      - /dev/dri
