version: "3"

services:
    secure-open:
        build: .
        ipc: host
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ./data:/app/data:ro
        devices:
            - /dev/snd
        environment:
            - DISPLAY=unix${DISPLAY}

